[tool.poetry]
name = "schemarrow"
version = "0.1.0"
description = "right out of the box mljar pipeline."
authors = ["DanielAvdar <66269169+DanielAvdar@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "schemarrow", from = "." },
]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
pandas = ">=2.0"
pyarrow = ">=7.0.0"
db-dtypes = {extras=["gcp"], version = ">=1",optional = true}

[tool.poetry.dev-dependencies]
pytest = ">= 7.1.2"
hypothesis = ">= 6.23.3"
pre-commit = ">= 2.20.0"
pytest-cov = ">= 4.0.0"
pylint = ">= 3"
mypy = ">= 0.991"
pylint-junit = ">= 0.3.2"
pylint-pytest = ">= 0.3.0"
pytest-parametrization = "^2022"
black = "*"
flake8 = "*"
isort = "*"

[tool.poetry.extras]
gcp = ['db-dtypes']

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"
