name: CI
on:
  pull_request:
    paths:
      - 'pandas_pyarrow/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
        numpy-version: [  '1.26', '2.0' , '2.1' , '2.2' ]
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry

      - run: poetry install
      - run: poetry add numpy==${{ matrix.numpy-version}}
      - run: poetry run pytest
    continue-on-error: true
