name: PR tests
on:
  pull_request:
    paths:
      - 'schemarrow/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [  '3.9', '3.10', '3.11', '3.12' ]
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        uses: abatilo/actions-poetry@v2

      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install the project dependencies
        run: poetry install

      - name: Unit Tests with Coverage
        run: poetry run pytest tests/unit --cov=schemarrow --cov-report=term-missing --cov-report=html

      - name: Save coverage report as HTML
        if: matrix.python-version == '3.11'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.os }}
          path: ./htmlcov

      - name: Install with integrations
        run: poetry install -E db-dtypes
      - name: All tests
        run: poetry run pytest

    continue-on-error: true
