name: CI
on:
  pull_request:
    paths:
      - 'pandas_pyarrow/**'
      - 'tests/**'
      - '.github/workflows/ci.yml'
      - 'pyproject.toml'
      - 'poetry.lock'
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: poetry

      - run: poetry install
      - run: poetry run pytest --cov=pandas_pyarrow --cov-report=xml
      - uses: codecov/codecov-action@v3
        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
    continue-on-error: true
